# Generated by Django 3.2.7 on 2021-09-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True, verbose_name='用户名')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('sex', models.CharField(max_length=1, null=True, verbose_name='性别')),
                ('mobile', models.CharField(max_length=30, null=True, verbose_name='手机号码')),
                ('address', models.CharField(max_length=150, null=True, verbose_name='地址')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'tbl_user_info',
            },
        ),
    ]
